### ISSUE TITLE
Feature: User can create a blog post

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a blog post, including an image url, summary, title, and body.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Upon logging in, I can click the Create A Post button, which leads to a form. Once filled out and submitted, I am redirected to the post view.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![image](https://user-images.githubusercontent.com/74282257/139963196-24182cb1-ca2d-42b3-b91d-396b91b22cb8.png)

Desktop
![image](https://user-images.githubusercontent.com/74282257/139963347-8201d58d-6d9f-471b-8536-194add5eb2f9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create the database for app
- [x] Import schema
        
### ☁️ Server

- [x] Update `server/index.js` to receive post requests from the user, and save data in table (post table)
        imageUrl
        summary
        title
        userId
        createdAt
        body
- [x] Test post requests with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a basic nav component
- [x] Create a component to allow a user to input a blog.
     - [x] Create container and row
             Create a form element
             Input for image url
             Input for summary
             Input for title
             Text area for body
             Cancel button that will discard form, and return user to previous window
             Submit button that will save user input, and switch to the blog entry

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
