### ISSUE TITLE
Feature: User can sign in

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign into their bloglab account.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once I create an account, I can use my credentials to log into my account.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop
![image](https://user-images.githubusercontent.com/74282257/141171615-5abe1114-f4f4-4467-a2f3-9165c094f115.png)

Mobile
![image](https://user-images.githubusercontent.com/74282257/141171582-faedb417-6263-48e2-b324-291b078fe009.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` with a post route for with path 'api/auth/sign-in
  - [x] Select sql query for userId, password, from users table where username = $1
  - [x] Define variable params as username in array literal
  - [x] db.query with args (sql, params)
  - [x] Handle result:
    - [x] Deconstruct array result.rows at first index into variable user
    - [x] Deconstruct user object into variable userId and hashedPassword
    - [x] return argon2.verify to verify hashedPassword from user against password from req.body
      - [x] Check if  result is matching
      - [x] On match, create the payload with userId, and username, and create token with jwt.sign(payload, process.env.TOKEN_SECRET
      - [x] Respond to client with token, and user (the payload)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update app.jsx component to 
  - [x] Create a handleSignIn method that sets the token to localStorage, and setState of user with a value of result.user
  - [x] Update render method to destructure method handleSignIn from the this object
  - [x] Include handleSignIn method inside of contextValue
- [x] Update auth-page.jsx to
  - [x] Destructure handleSignIn method from this.context
  - [x] Update props for AuthForm to have onSignIn={handleSignIn}
- [x] Update auth-form.jsx to:
  - [x] handleSubmit method to handle the result of the res.json()
    - [x] If action is sign up, then redirect user to sign in page window.location.hash = 'sign-in'
    - [x] Otherwise if result.user && result.token are both truthy, execute this.props.OnSignIn(result) --- passing the result as argument
  - [x] Update render method
    - [x] Create ternaries to dynamically change whether or not log in or sign up is displayed (since auth-form.jsx is sharing both sides)
    - [x] Update the values of the React Elements and hrefs as needed

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
