### ISSUE TITLE
Feature: User can sign out

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop
![image](https://user-images.githubusercontent.com/74282257/141195074-05096f4b-ac53-49b4-8618-b00af37a6694.png)

Mobile
![image](https://user-images.githubusercontent.com/74282257/141195118-8e6bb4ac-c272-45d4-aaa6-75086c958aec.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update app.jsx component to:
  - [x] Create handleSignOut method that removes the token and sets user to null
  - [x] Bind method to App class
  - [x] In render method
    - [x] Object destructure -- create variable handleSignOut from this.handleSignOut
    - [x] Add handleSignOut to contextValue
- [x] Update navbar.jsx component to:
  - [x] Destructure handleSignOut and user from this.context
  - [x] Add react element for sign out button
  - [x] Add condition to check if a user exists
    - [x] If the user does not exist
      - [x] Create a sign out anchor with fontawesome sign out icon
      - [x] On click of the sign out icon, call the handleSignOut method passed from context

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
