### ISSUE TITLE
Feature: User can update a blog post

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their blog posts.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a mistake was made during creating a post, I can find my post on my home screen, go to my posts, and click the edit button to begin editing.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![image](https://user-images.githubusercontent.com/74282257/141392284-4d7936b0-636f-408d-927f-b58a6ae51133.png)

Desktop
![image](https://user-images.githubusercontent.com/74282257/141392193-d2cb5624-243c-4bc9-bace-7d7febf316a0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a put route on path /api/posts/:postId and add authorization middleware to check userId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to handle editing existing blog posts (redirect from the edit icon on home page)
- [x] When switching to the edit-form.jsx send a get request on componentDidMount to populate the information for the edit post.
- [x] On submit of the form send the put fetch request to the server with the new information.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
