### ISSUE TITLE
Feature: User can delete a blog post

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a blog post.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If I no longer want to keep a post, I can access the delete button inside of the edit form.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![image](https://user-images.githubusercontent.com/74282257/141532318-17b7f526-21fd-4488-9992-325d942f18ee.png)

Desktop
![image](https://user-images.githubusercontent.com/74282257/141532373-515bd2d5-8706-488a-8f3a-174af996d6eb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a delete route to `'/api/posts/:postId'`
- [x] Get postId from req. params
- [x] Use authorizationMiddleware to confirm userId in token
- [x] Get userId from req.user
- [x] Send sql to delete where postId matches the postId from params
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update edit-form.jsx component to include a delete button that opens a modal to confirm deletion.
- [x] Upon confirmation of delete (click of delete button) fetch delete request sent to route for deletion of the post with the given postId.
- [x] Supply token for authorization middleware

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
