### ISSUE TITLE
Feature: User can view list of their blogs

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can retrieve a list of their blog entries.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once I click "My Posts" on the home page, I am redirected to a list of blogs I have created.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop
![image](https://user-images.githubusercontent.com/74282257/141389862-ccc93fb5-9beb-4d88-bd92-a91d1c31e1a1.png)

Mobile
![image](https://user-images.githubusercontent.com/74282257/141389934-bebe48bd-195b-4365-9c5b-6a88e09d74c5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to get all blog posts of the userId from jwtToken.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update component with a fetch (get) to '/api/my-posts' with the token inside the req.header.
- [x] Store the userPosts inside of state
- [x] Create button for "My Posts"
- [x] Create a condition that will map over all posts or user posts (from state) based on clicking the anchor for "Your Feed" or "My Posts".

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
