### ISSUE TITLE
Feature: User can read a blog post

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can read blog posts.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

I am able to view the post I created.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile

![image](https://user-images.githubusercontent.com/74282257/140233463-0fc10c0f-42cf-45ee-85c3-e343f28cf83d.png)

Desktop

![image](https://user-images.githubusercontent.com/74282257/139969492-a223bb11-8aa2-4eb1-b3d5-ffb5628333b1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ☁️ Server

- [x] Update `server/index.js` with an get request to retrieve
        imageUrl
        summary
        title
        username
        createdAt
        body
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Implement window location hashing functionality in app.jsx
- [x] Conditional rendering for Form component or Blog component
- [x] Create a Blog component to display the users post on submit
     - [x] Create container and row
     - [x] Image element for image url data
     - [x] Text element for summary data
     - [x] Heading element with title data
     - [x] Text element with username
     - [x] Text element with createdAt (reformatted) date 
     - [x] Text element for the body data

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
