### ISSUE TITLE
Bug: No Results Page allowed non-users to click "New Post" button that led to form.

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#30]
#### Desired Behavior

> ##### The app should ...

Show a disabled button if user is null.
#### Actual Behavior

> ##### The app does this instead ...

The app shows an active button that leads to a form for post creation. Upon submission a 500 error is reported and the app crashes.
#### Steps to Reproduce

> ##### To trigger the bug, you must ...

1. Be logged out
2. Navigate to home page
3. Click the "NEW POST" button, colored in blue
4. Fill form
5. Submit
6. App crashes

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Move NoResults from home.jsx to it's own component in page directory
- [x] Convert from function component to class component for ease of use.
- [x] Pass user as a prop from app.jsx to home.jsx to no-results.jsx
- [x] Check if there is a user logged in
- [x] If user is null, add the disabled class to the anchor element and also remove the href. 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
