### ISSUE TITLE
Feature: User can browse all blogs

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view posts from all users and their respective posts.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

I have access to a blog feed, and my posts. When clicking into the card, I can read it.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/74282257/140251596-118d209e-87be-4fe5-a9cf-17edbf1040d9.png)
![image](https://user-images.githubusercontent.com/74282257/140251619-db5caa34-ef45-4408-83e8-5cd67d6ec758.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a get route for all posts
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Home component to represent all blog posts "Your Feed"
- [x] Map over each post and make a corresponding materialize card based on the postId
- [x] Add button for Create a Post and reference the href as '#form' for view swapping
  - [x] Make button full width of div (same size as the card) 
- [x] Update conditional render to Home component for if route.path is ''.
- [x] Add conditional render to Form component for if route.path is 'form'.
- [x] Preserve line spacing in blogview component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
