### ISSUE TITLE
Feature: User can comment on blog posts

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can comment on blog posts.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

I can interact with a blog post by leaving a comment, and having a discussion.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![image](https://user-images.githubusercontent.com/74282257/140425277-f121259d-71c0-4ee4-9762-4ad487c7f212.png)

Desktop:
![image](https://user-images.githubusercontent.com/74282257/140425360-5f30ba00-f6a1-4c98-8df6-81e96b332ff0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a post route for the comments table (send a nested db.query for the username in the users table)
  - [x] SQL query will require a join of the comments table with the users table (userId) and the posts table (postId)
- [x] Update `server/index.js`with a get route to retrieve all comments for a specific post
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component "CommentsForm" to handle comments for a blog post
- [x] Update renderPage method to render Comments component on route.path 'comments'
- [x] Update BlogView component and add a comment icon that has an href to #comments?postId=${postId}
- [x] Create a CommentList component to render comments for a given post
  - [x] Use a count aggregate function to display the number of comments for a given post and display on BlogView component
- [x] Attach new comment to the comments array and set it as the new comment's state.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
