### ISSUE TITLE
Feature: User can like blog posts

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like blog posts.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When I like a post, the heart will fill in, and the like counter will go up indicate that the "like" was successful.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![image](https://user-images.githubusercontent.com/74282257/140626797-d7bd05ab-53e1-49aa-a885-bc8b70e4ec49.png)

Desktop
![image](https://user-images.githubusercontent.com/74282257/140626872-372ad9ed-e82a-4b17-a76d-a48dac92febd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to make userId and postId unique, so that a user cannot contribute more than one like.
  - [x] Add to sql "on conflict do nothing"

### ☁️ Server

- [x] Update `server/index.js` to send a post route to "likes" table with the "userId" where the post is that postId. 
- [x] Update `server/index.js` to send a delete route to "likes" table when someone unlikes the post with a specific postId
- [x] Update `server/index.js` to send a get route to "likes" table to count all rows in the "likePosts" table with a specific postId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update blogview component add a heart icon
- [x] On click, if the post is not currently liked then send the post request 
- [x] On click, if the post is already liked, then send a delete request
- [x] Add to a counter for the number of likes that changes when user/client likes.
- [x] Make the counter update live

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by kenkieu** [comment]
![Kapture 2021-11-08 at 14 46 47](https://user-images.githubusercontent.com/74282257/140830597-f6248852-4f6a-4a57-811f-6cfc1b8c1ee4.gif)

**Comment by kenkieu** [comment]
![Kapture 2021-11-08 at 14 46 47](https://user-images.githubusercontent.com/74282257/140830711-a5b357a1-e384-45bd-9746-7432101434bd.gif)

**Comment by kenkieu** [comment]
![Kapture 2021-11-08 at 14 53 08](https://user-images.githubusercontent.com/74282257/140831061-8bb73db7-4873-4a27-8658-a8b51fcb1dd6.gif)
