### ISSUE TITLE
Feature: User can copy the blog post link

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can copy the blog post link.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking the "link" button, I can copy the link to share to other social media websites.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop
![image](https://user-images.githubusercontent.com/74282257/140839572-c22cd356-adc2-4de6-9e37-03ae8aa69d54.png)

Mobile
![image](https://user-images.githubusercontent.com/74282257/140839530-a3005267-7afb-4df7-b06e-d12f6489fddb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a button inside of the blogview component with a copy icon
- [x] onClick, the button will save the window.location.href in the user's clipboard

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
