### ISSUE TITLE
Feature: User can send the blog to their email

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop
![image](https://user-images.githubusercontent.com/74282257/140982293-adefe3b3-2f56-4eff-b194-203246ff82ea.png)

Mobile
![image](https://user-images.githubusercontent.com/74282257/140982241-69c0df1c-5f6a-435a-b89c-1057565ca27f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Install sendgrid as a dependency
- [x] Require or import into index.js
- [x] Update app.get('api/posts:postId) route to also include user's email
- [x] Update `server/index.js` with the sendgrid client to respond to client/user clicking the email button on front end.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update component blogview with a gray email button
- [x] Create a method that is sends a POST request to the server
  - [x] Add the necessary info to the req.body of the post (user's email, title, body)
  - [x] On click make the button green to notify the user that it's been sent

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
