### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by kenkieu** [kenkieu/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for a bloglab account.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

I can sign up for an account by providing a username, password, and email address!
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Desktop
![image](https://user-images.githubusercontent.com/74282257/141171433-99a547f6-e80b-4eb9-8099-07f1ceadbe2b.png)

Mobile
![image](https://user-images.githubusercontent.com/74282257/141171465-802d40e7-78fb-4e12-bf59-4e1d0e2a2e1a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a post route for user sign up
  - [x] Hash password using argon2.hash(password)
  - [x] Handle response with sql insert query
  - [x] Respond with status(201).json(user) -- user being the result.rows[0]
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update app.jsx state to have isAuthorizing: true by default
- [x] On mount set the hash route
  - [x] Define the token, if it's null, setState of user (null at this point),  isAuthorizing to false
- [x] If isAuthorizing is false, wrap current render (nav, and this.renderPage) inside AppContext.Provider with prop of value = {contextValue}
- [x] Create Auth page component
  - [x]  Nest Auth Form inside and pass props key={route.path}, action={route.path}, onSignIn={handleSignIn}
  - [x] Add AuthPage.contextType = AppContext at bottom
- [x] Create AuthForm component to Sign Up
  - [x] Create a handleChange and handleSubmit method (submit will have post fetch for username and password, and email)
    - [x] Check if user is signing up, and if so lead them to the login hash route
    - [x]  Add alll react element to render the sign up page
  - [x] Update app.jsx to include a route.path for Auth page.
  - [x] Create Provider in app.jsx and share context

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
